project:
  type: book
  output-dir: docs

profile:
  default: web
  group:
    - [web, docx]

book:
  title: "Legal Tech, Manual del Curso"

bibliography: bibliografia.bib
suppress-bibliography: true

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    css: styles.css
    include-in-header:
      - _includes/gtm-head.html
    include-before-body:
      - _includes/gtm-body.html
