project:
  type: book
  output-dir: docs

book:
  title: "Legal Tech, Manual del Curso"

  chapters:
    - index.qmd
    - parte-0/profesores.qmd
    - parte-0/intro.qmd

    - part: "parte-1-modulo-1/00-presentacion.qmd"
      chapters:
        - parte-1-modulo-1/01-capitulo.qmd
        - parte-1-modulo-1/02-capitulo.qmd
        - parte-1-modulo-1/03-capitulo.qmd
        - parte-1-modulo-1/04-capitulo.qmd

    - part: "parte-2-modulo-2/00-presentacion.qmd"
      chapters:
        - parte-2-modulo-2/05-capitulo.qmd
        - parte-2-modulo-2/06-capitulo.qmd

    - part: "parte-3-modulo-3/00-presentacion.qmd"
      chapters:
        - parte-3-modulo-3/07-capitulo.qmd
        - parte-3-modulo-3/08-capitulo.qmd

    - part: "parte-4-modulo-4/00-presentacion.qmd"
      chapters:
        - parte-4-modulo-4/09-capitulo.qmd
        - parte-4-modulo-4/10-capitulo.qmd
        - parte-4-modulo-4/11-capitulo.qmd

    - part: "tutoriales/00-presentacion.qmd"
      chapters:
        - tutoriales/instalar-python.qmd
        - tutoriales/visual-studio-code.qmd
        - tutoriales/git-y-github.qmd
        - tutoriales/licencias-y-reutilizacion.qmd
        - tutoriales/github-pages.qmd

    - referencias.qmd

bibliography: bibliografia.bib
suppress-bibliography: true

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    css: styles.css
    include-in-header:
      - _includes/gtm-head.html
    include-before-body:
      - _includes/gtm-body.html
